### ISSUE TITLE
实验四的进程间通信

### ISSUE THREAD

**Issue by ShuquanWei** [benzoin-p/OS-D#1]
作者你好，我下载了你的代码并在Ubuntu操作系统下运行，运行时在控制台只打印了Key的值，而消息似乎没有接收成功，而程序也没有运行结束并退出，我查看消息队列，发现每运行一次确实能向队列中增加3条消息，但是子进程似乎读不到任何消息。是我的环境有问题吗？请你有空回答一下我的问题，不胜感激！

**Comment by benzoin-p** [comment]
按理来说子进程返回以后程序才会运行结束并退出，没退出可能子进程中的变量ret未取到值。但读不到消息的情况我没有遇到过，正常情况下程序会输出如下内容：
key = [1e03326d]
msgid = [0]
recv msg =[Test1]
recv msg =[Test2]
recv msg =[Test3]

**Comment by ShuquanWei** [comment]
对，正常情况应该是你写的那样，输出完后程序才结束退出
但是我运行后，只打印了key值，如下：
key = [某某某]
//这里也获取到了msgid = [0]

然后程序就阻塞了。你说的“变量ret未取到值” 是不是msgrcv函数没有成功调用呀🤔

经过我的不断调试，程序输出上面两行好像就开始假死阻塞了（沧桑.jpg）






Everything&nbsp;going
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "benzoin-p/OS-D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 晚上10:40
***@***.***&gt;;
抄送:&nbsp;"Everything ***@***.******@***.***&gt;;
主题:&nbsp;Re: [benzoin-p/OS-D] 实验四的进程间通信 (Issue #1)





 
按理来说子进程返回以后程序才会运行结束并退出，没退出可能子进程中的变量ret未取到值。但读不到消息的情况我没有遇到过，正常情况下程序会输出如下内容：
 key = [1e03326d]
 msgid = [0]
 recv msg =[Test1]
 recv msg =[Test2]
 recv msg =[Test3]
